Tests for list of payments
apmath-web/credit-bdd pull request #12
Opened 2018-11-06 01:41 UTC by BarracudaPff

- [x]  create mocks

- [x ] write bdd tests

close #4

2018-11-06 06:20 UTC, malinink commented
@BarracudaPff 
Мысли интересные, но, т.к. мы тестируем черный ящик, то прийдется выполнить все действия.
Я бы проверял работу метода следующий образом:

- Создал минимальный по сроку кредит, запомнил id.
  1. Сверил список всейх платежей (все 6)
  2. Сверил список прошедших (пустой)
  3. Сверил следующий (первый)
  4. Сверил все предстоящие платежи (6 штук)
- Погасил бы первый платеж
  1. Сверил список всейх платежей (6, первый оплачен)
  2. Сверил список прошедших (1)
  3. Сверил следующий (второй)
  4. Сверил все предстоящие платежи (5 штук)
- Погасил бы все платежи
  1. Сверил список всейх платежей (6, все оплачены)
  2. Сверил список прошедших (все)
  3. Сверил следующий (0)
  4. Сверил все предстоящие платежи (0)
- Закрыл кредит
  1. Сверил список всейх платежей (не доступен)
  2. Сверил список прошедших (не доступен)
  3. Сверил следующий (не доступен)
  4. Сверил все предстоящие платежи (не доступен)

2018-11-07 05:24 UTC, BarracudaPff commented
Я конечно могу написать это как вы и сказали, но тогда тут будет еще +много файлов и call'ов, потому что миллион строчек писать в тестах не хочется (eval if-ами и огромными функциями), а другого пути я не вижу... Кстати тест все еще будет 1, ну может максимум 2.

И я надеюсь в тесте не нужно выписывать точные значения ответов и формулы вбивать

2018-11-07 05:25 UTC, BarracudaPff commented
Вопрос - продолжать с ветвлением тестов call'ами?

2018-11-07 08:00 UTC, malinink commented
@BarracudaPff 
Пока что достаточно, давайте я подумаю как быть с таким случаем.

2018-11-07 14:02 UTC, malinink commented
@BarracudaPff 
Немного поразмыслил, предлагаю пообсуждать немного.
А что если: Создать в моке, большой массив, всех необходимых состояний платежей.
При создании кредита - устанавливать индекс в 0, При любом погашении - увеличивать на 1.
При доступе к платежам, получать соответствующий индекс массива и возвращать в необходимом формате.
Соответственно в большом массиве будут заполнены только те значения, на которые мы будем запрашивать списки.
0 - создание
1 - после 1 платежа
5 - после последнего платежа
Что скажете? Будет ли удобным такой подход?

План Б: можно попробовать написать тест без мока.

2018-11-07 14:52 UTC, BarracudaPff commented
@malinink 
Интересный подход, могу реализовать. Хотя я нашел решение своей проблемы, так что можно сделать все это без обходов.
Правда сценарий выглядит слишком большим, можно его за-loop'ить.
У меня сейчас 3 варианта

1.  Писать весь мок в одном файле с небольшими `js-функциями` по типу "найти в массиве", тогда этот мок будет страшно выглядеть

1.  Создать папку **get-payments-mock** и выносить `*.js` и `*feature`  в отдельные файлы, там с ними гораздо легче работать и сам мок будет красивее

1.  Обойти проблему как вы и предложили, но тогда добавлять новые тесты будет почти нереально

2018-11-07 14:53 UTC, BarracudaPff commented
@malinink 
Что же лучше?)

2018-11-08 18:09 UTC, malinink commented
@BarracudaPff Извиняюсь, вчера уже небыло времени, а сегодня весь день напряжный, только сейчас нашел время.

Итак, мне, внутренне больше всего нравится вариант 3. Если он и по времени наименее труднозатратен - то вообще идеально.

А файл с данными можно, действительно, вынести. Сценарий пока оставить один. Проблемы в других тестах предлагаю решать по мере поступления. Может быть и надумаем какой-то общий механизм, пока не понятно какой => Итерируемся.

2018-11-10 07:45 UTC, malinink requested changes

2018-11-10 07:45 UTC, malinink commented on tests/bdd/get-payments-test.feature
> +    Then status 200
@BarracudaPff @Meleorina 
Так, а проверка тела?

2018-11-12 04:54 UTC, BarracudaPff commented
Сделал match, надеюсь внутрь массива смотреть не надо

2018-11-12 07:05 UTC, malinink commented
@BarracudaPff 
Конечно надо, надо убедится что там корректные данные, мы вроде как обсуждали на паре!

2018-11-12 13:22 UTC, BarracudaPff commented on tests/bdd/get-payments-test.feature
> +    Then status 200
Добавил

2018-11-18 18:39 UTC, malinink requested changes
Нет опять не то,
необходимо написать правильный тест, и в тесте необходимо проверить все цифры.
ещё раз:
 - создали новый, проверили все вариации запросов.
 - совершили 1 платеж, проверили опять все вариации
 - совершили все платежи, проверили все вариации
 - удалили кредит, проверили все вариации

2018-11-18 18:39 UTC, malinink commented on tests/bdd/get-payments-test.feature
> +    Given request {"payment":172600.00,"type":"regular","currency":"RUB","date":"2018-01-01"}
не пройдет, платеж не может быть раньше даты начала кредита же, что-то не консистентно

2018-12-08 07:09 UTC, malinink commented
@BarracudaPff какое-то движение будет?

2019-02-12 19:09 UTC, merged