Feature 7
apmath-web/credit-bdd pull request #13
Opened 2018-11-06 19:55 UTC by morozzArt

- [ ] Create test

- [ ] Create mock

2018-11-18 18:17 UTC, malinink requested changes

2018-11-18 18:17 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    Given path 5
Я бы проверил 1 раз, но перед тем как убедится что вернется 404 на удаление, проверил бы что запрос на возращение результатов по кредиту возвращает тоже 404, т.е. эта проверка на то что такого кредита действительно небыло создано

2018-11-18 18:17 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    Then status 204
А вот и нет, мы удалять можем только закрытые кредиты.
Подумайте сколько и каких проверок должно быть, чтобы тест проверял все кейсы

2018-11-18 18:17 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    * url 'http://localhost:' + serverMock.port + '/credit' + '/delete'
однообразные тесты лучше делать с экзамплами, можно в отдельных сценариях.

2018-11-22 19:57 UTC, morozzArt commented
@malinink , готово к проверке

2018-11-23 06:09 UTC, malinink requested changes

2018-11-23 06:09 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    Given path 5
я бы побольше идентификатор указал, для устойчивости тестирования на реальном сервисе, что-нибудь ближе к 1000.

2018-11-23 06:09 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    Then status 400
формат ответа тоже  нужно проверить, он должен соответствовать спеке.

2018-11-23 06:09 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    * url 'http://localhost:' + serverMock.port + '/credit' + '/delete'
Может быть я не заметил в прошлый раз, но по спеке url другой. (без /delete)

2018-11-23 06:09 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    When method put
не понял что проверяем? у нас нет такого действия

2018-11-23 06:09 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    * url 'http://localhost:' + serverMock.port + '/credit' + '/delete'
/delete лишний

2018-11-23 06:09 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    When method delete
так опять не удалится, почему должен?

2018-11-23 06:10 UTC, malinink commented
@morozzArt Если готово - меняйте лейбл тоже, проверил, много недочетов.

2018-11-29 20:29 UTC, morozzArt commented on tests/bdd/close-credit-test.feature
> +    When method put
В методе "Check on validation" мы делаем:
1) Создание кредита
2) Удаление незакрытого кредита - получаем 404
3) Вносим последний платеж , для этого используем метод put(взято из спеки)
4) Успешно удаляем кредит - получаем 204

2018-11-29 20:30 UTC, morozzArt commented on tests/bdd/close-credit-test.feature
> +    When method delete
Потому что мы внесли методом put последний платеж(брали кредит на 1 месяц)

2018-11-30 08:00 UTC, malinink commented
@morozzArt 
Зачем закрыли issue #6 Почему убрали ссылку отсюда на него?

2018-11-30 19:46 UTC, malinink requested changes

2018-11-30 19:46 UTC, malinink commented on tests/bdd/close-credit-test.feature
> +    Then status 200
метод put без тела ничего не снимет, необходимо передать корректные параметры

2019-02-12 19:09 UTC, merged