Tests for сredit's payments
apmath-web/credit-bdd pull request #15
Opened 2018-11-09 13:59 UTC by EeOneDown

- [ ] Create mocks
- [ ] Write bdd

2018-11-09 21:33 UTC, EeOneDown commented on tests/bdd/write-off-payment-test.feature
> -  #Delete credit
@anatolyefimov Почему удалил? Мы же делаем полный цикл жизни кредита - создание, проведение платежей и удаление
К тому же, в реальном проекте этот тестовый кредит останется висеть в памяти

2018-11-10 07:50 UTC, malinink requested changes
Я пока что посмотрел не мок, а сам тест.
Меня он почти устраивает, но есть один момент. Необходимо проверить что платежи корректно списываются, для проверки предлагаю запрашивать список платежей, с фильтром - следующий платеж, и проверять по нему что списание прошло, и след плажет тот, который ожидается.
В случае досрочного погажения эта проверка еще более актуальна, например что следующий платеж изменился, т.е. изменился объем платежа. Если есть необходимость проверить их количество - то тоже необходимо проверять.

2018-11-18 18:33 UTC, malinink requested changes

2018-11-18 18:33 UTC, malinink commented on tests/bdd/write-off-payment-test.feature
> +    And match response == {"payments":[{"type":"regular","state":"next","date":"2018-01-01","payment":169106.00,"percent":4167.00,"body":164939.00,"remainCreditBody":835061.00}]}
Решили для упрощения использувать целые числа везде, поменяйте плз, также в файле изменилась формула округления, вы учли это?

2018-11-18 18:33 UTC, malinink commented on tests/bdd/write-off-payment-test.feature
> +  #Perfrom early payment
надо ещ проверить что early  проходит в том числе и на дату соверщения платежа, заменяя его собой.

2018-11-23 20:34 UTC, EeOneDown commented on tests/bdd/write-off-payment-test.feature
> +    And match response == {"payments":[{"type":"regular","state":"next","date":"2018-01-01","payment":169106.00,"percent":4167.00,"body":164939.00,"remainCreditBody":835061.00}]}
Исправил на целые числа и пересчитал по новой формуле. Если не ошибся с early, то всё должно быть верно.

2018-11-23 20:47 UTC, EeOneDown commented on tests/bdd/write-off-payment-test.feature
> +  #Perfrom early payment
Честно говоря, немного запутался с early. Можно попросить на паре продемонстрировать оба варианта с early?

2018-11-24 06:56 UTC, malinink commented on tests/bdd/write-off-payment-test.feature
> +  #Perfrom early payment
Конечно, рассмотрим на паре

2018-11-30 22:20 UTC, EeOneDown commented
Упс, забыл, что уменьшаем сумму платежа, а не срок кредита.

2018-12-03 18:27 UTC, malinink approved these changes
Вроде как больше проблем нет

2018-12-03 18:28 UTC, merged