Feature 1
apmath-web/credit-bdd pull request #2
Opened 2018-10-11 09:48 UTC by levozavr

Here is some tests for BDD methodology. And some mock servers for checking tests

2018-10-11 09:51 UTC, levozavr commented
May be i wrote some overhead in tests and  we don't need to it.

2018-10-11 10:48 UTC, malinink requested changes
Да, также необходимо проработать кейсы с не корректными данными или не соответствующими формату, например отрицательный кредит или число вместо строки имени

Опять же, все некорректные наборы данных можно запаковать в набор и для него написать сценарий.

2018-10-11 10:48 UTC, malinink commented on tests/bdd/mocks/take-credit-mock.feature
> +"""
Я бы сделал функцию inline, а лучше бы вообще отказался от неё. т.к. используется в одном месте.

2018-10-11 10:48 UTC, malinink commented on tests/bdd/mocks/take-credit-mock.feature
> +    * def response = credits[str2int(pathParams.id)]
вроде как везде используется что-то вроде `[pathParams.id + '']` попробуйте, выглядит странно, согласен, но возможно удобнее нежели функция отдельная.

2018-10-11 10:48 UTC, malinink commented on tests/bdd/take-credit-test.feature
> +    Then status 200
добавбье EOF

2018-10-11 10:48 UTC, malinink commented on tests/bdd/mocks/take-credit-mock.feature
> +    * def credit = request
я бы ещё проверял формат запроса, т.е. наличие необходимых параметров и их типы

2018-10-11 10:48 UTC, malinink commented on tests/bdd/take-credit-test.feature
> +Scenario: create credit #1
есть такая штука - как data, вы можете брать различные параметры и на их наборе повторять сценарий. Я так понял что сценарии отличаются только данными - поэтому, если есть желание - предлагаю изучить и применить, если нет - убрать второй сценарий.

2018-10-11 12:58 UTC, levozavr commented on tests/bdd/mocks/take-credit-mock.feature
> +    * def response = credits[str2int(pathParams.id)]
Это не сработало, так как мне надо было превратить string в int, а не наоборот

2018-10-11 15:11 UTC, levozavr commented
У меня проблема, локально весь код работает так как надо, но почему то на travis  он работает не так.... Это как то странно....

2018-10-11 15:16 UTC, levozavr commented
```
  keys = ["person", "credit", "agreementAt","currency","duration","percent"];
  for (var i = 0, len = keys.length; i < len; i++){
    var key = keys[i]
    console.log(key)
    console.log(key in request)
    if (!(key in request)){
      return{"code":400, "message":"Parametr missed"};
    }
  }

```
Этот код работал некорректно на **travis**

2018-10-11 15:19 UTC, levozavr commented
Вроде как все работает, посмотрите, пожалуйста

2018-10-11 18:28 UTC, malinink commented on tests/bdd/mocks/take-credit-mock.feature
> +    * def response = credits[str2int(pathParams.id)]
А я понял почему, потому что складываете в массив с целым ключем, а можно по-аналогии по строке класть. либо, есть альтернатива, складывать число  и брать число, не уверен, но можно попробовать что-то вроде `+ 0`  вместо `+ ''` это же JS...

2018-10-11 19:27 UTC, malinink commented
@levozavr нашел хороший пример с Id - https://github.com/intuit/karate/blob/933d3803987a736cc1a38893e7039c4b5e5132fc/karate-demo/src/test/java/mock/micro/cats-mock.feature
По проверке - это очень хорошо, но как нибудь бы всю проверку по типизации завернуть в что-нибудь похожее на `bodyMatches`, и тогда выглядело бы всё это дело так:
 - объявляем метод, который работает с постом где тело матчит требуемое, и там процессим.
после добавляем такой же метод, но без матча на тело, и в нем возвращаем 400 ошибку всегда.

Но я пока что решения не нашел.

Вы сделали хорошо, но я предполагаю что слишком много кода.

Также я скоро обновлю немного базовый мок, там будут более строгие условия, примените к себе плз.

2018-10-11 20:05 UTC, malinink commented
Я немного подумал, видимо для моков не поддерживаются негативные сценарии. Давайте оставим только позитивные, ну а негативных надо будет добавить после реализации.
В принципе мы их и сейчас сможем добавить, только мок для них написать не сможем норально.

Поэтому предлагаю не морочить вам и себе голову, @levozavr  что скажете?

2018-10-12 14:23 UTC, levkovalenko commented
Вроде как все подправил, проверьте пожалуйста.

2018-10-12 18:54 UTC, malinink approved these changes

2018-10-12 18:55 UTC, merged